# 数组类型

之前已经看过整数数组和布尔数组，除此之外还有浮点数数组和复数数组。

In [1]:
from numpy import *

## 复数数组

产生一个复数数组：

In [2]:
a = array([1 + 1j, 2, 3, 4])

python会自动判断数据的类型，

In [3]:
a.dtype

dtype('complex128')

对于复数我们可以查看它的实部和虚部：

In [4]:
a.real

array([1., 2., 3., 4.])

In [5]:
a.imag

array([1., 0., 0., 0.])

设置虚部的值

In [6]:
a.imag = [1,2,3,4]
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [7]:
#查看复共轭 
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

事实上，这些属性方法可以用在浮点数或者整数数组上

In [8]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [9]:
a.real

array([0., 1., 2., 3.])

In [10]:
a.imag

array([0., 0., 0., 0.])

In [11]:
a.conj()

array([0., 1., 2., 3.])

在浮点数或者整数数组上,复数部分是只读的，不能修改

In [12]:
a.imag=[1,2,3,4]

TypeError: array does not have imaginary part to set

## 指定数组类型

在构建数组时可以制定数组类型

In [13]:
a = array([1,2,3,4],dtype='float64')
a

array([1., 2., 3., 4.])

0-255 的数字可以表示ASCⅡ码，我们可以用 ord 函数来查看字符的ASCⅡ码值：

In [14]:
ord('s')

115

从数据中读入，并执行数据类型

In [15]:
b = frombuffer("foo",dtype=uint8)
b

array([102, 111, 111], dtype=uint8)

还可以指定任务数据类型的数组

In [18]:
a = array([[1,2,3,4],"hello",2.3],dtype=object)
a

array([list([1, 2, 3, 4]), 'hello', 2.3], dtype=object)

## 类型转换


In [19]:
a = array([1.5, -3], 
         dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

### asarray 函数

使用 asarray 函数，asarray 不会修改原来数组的值：

In [20]:
asarray(a,dtype=float64)

array([ 1.5, -3. ])

In [21]:
a

array([ 1.5, -3. ], dtype=float32)

但当类型相同的时候，asarray 并不会产生新的对象，而是使用同一个引用：

In [24]:
b = asarray(a, dtype=float32)
b is a

True


### astype 方法

astype 方法返回一个新数组，astype也不会改变原来数组的值

In [29]:
a = array([1.5, -3], 
         dtype=float32)
a.astype(float64)

array([ 1.5, -3. ])

In [30]:
a

array([ 1.5, -3. ], dtype=float32)

In [31]:
b = a.astype(float64)
b is a

False

In [32]:
b = a.astype(float32)
b is a

False

astype 总是返回原来数组的一份复制，即使转换的类型是相同的

### view 方法

In [33]:
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4], dtype=int32)

view 会将 a 在内存中的表示看成是 uint8 进行解析：

In [35]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [36]:
a[0] = 2**30
a

array([1073741824,          2,          3,          4], dtype=int32)

修改 a 会修改 b 的值，因为共用一块内存：

In [37]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)