# 数组方法

In [14]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 求和

In [15]:
a = array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

求所有元素的和：

In [16]:
sum(a)

36

指定维度求和,沿着第一维度求和：

In [17]:
sum(a,axis=0)

array([ 6,  8, 10, 12])

In [18]:
sum(a,axis=1)

array([10, 26])

或者使用a.sum()方法

In [19]:
a.sum(axis=0)

array([ 6,  8, 10, 12])

## 求积

求所有元素的乘积

In [20]:
a.prod()

40320

In [21]:
a.prod(axis=0)

array([ 5, 12, 21, 32])

## 求最大值 最小值

In [22]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
a

array([[0.863, 0.962, 0.559, 0.7  ],
       [0.655, 0.383, 0.476, 0.97 ],
       [0.785, 0.018, 0.634, 0.561]])

求全局最大值或最小值

In [23]:
a.max()

0.9699443600503788

In [24]:
a.min()

0.018345947470265078

求某个维度上的最大值或最小值

In [25]:
a.max(axis=0)

array([0.863, 0.962, 0.634, 0.97 ])

In [26]:
a.min(axis=1)

array([0.559, 0.383, 0.018])

## 求最大值 最小值的位置

使用 argmin, argmax 方法：

In [27]:
a.argmin()

9

In [28]:
a.argmin(axis=0)

array([1, 2, 1, 2])

## 均值

可以使用 mean 方法

In [29]:
a = array([[1,2,3],[4,5,6]])
a.mean()

3.5

也可以使用mean(a)函数

In [30]:
mean(a)

3.5

In [31]:
mean(a,axis=0)

array([2.5, 3.5, 4.5])

还可以使用 average 函数

In [32]:
average(a, axis = 0)

array([2.5, 3.5, 4.5])

average 函数还支持加权平均

In [33]:
average(a, axis = 0, weights=[1,2])

array([3., 4., 5.])

## 标准差和方差

用 std 方法计算标准差：

In [34]:
a.std()

1.707825127659933

In [35]:
a.std(axis=1)

array([0.816, 0.816])

使用var方法或var（）计算方差：

In [36]:
var(a, axis=1)

array([0.667, 0.667])

In [37]:
a.var(axis=1)

array([0.667, 0.667])

## clip方法

使用clip把数值限制在某个范围

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# 小于3的重置成3，大于5的重置成5
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## 最大值和最小值之差 

计算最大值和最小值之差：

In [40]:
a.ptp()

5

In [41]:
a.ptp(axis=0)

array([3, 3, 3])

## round 方法

近似，默认到整数：

In [44]:
a = array([1.35, 2.5, 1.5,1.68])
a.round()

array([1., 2., 2., 2.])

注意 这里的.5的近似规则为近似到偶数值

近似到一位小数

In [45]:
a.round(decimals=1)

array([1.4, 2.5, 1.5, 1.7])