# 数组形状


In [16]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 修改数组形状

In [17]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

将形状修改为2乘3

In [18]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

与之对应的方法是 reshape ，但它不会修改原来数组的值，而是返回一个新的数组：

In [19]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
a

array([[0, 1, 2],
       [3, 4, 5]])

shape 和 reshape 方法不能改变数组中元素的总数，否则会报错

## 使用 newaxis 增加数组维数

In [21]:
a = arange(3)
a

array([0, 1, 2])

In [22]:
shape(a)

(3,)

In [23]:
y = a[newaxis, :]
shape(y)

(1, 3)

In [24]:
y

array([[0, 1, 2]])

根据插入位置的不同，可以返回不同形状的数组

In [25]:
y = a[:,newaxis]
shape(y)

(3, 1)

## squeeze 方法去除多余的轴

In [26]:
a = arange(6)
a.shape = (2,1,3)
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [27]:
b = a.squeeze()
b.shape

(2, 3)

In [28]:
b

array([[0, 1, 2],
       [3, 4, 5]])

squeeze 返回一个将所有长度为1的维度去除的新数组。

## 数组转置

使用 transpose 返回数组的转置，本质上是将所有维度反过来：

In [29]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [30]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [31]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [32]:
b = array([1,2,3,4])
b.T

array([1, 2, 3, 4])

注意：

* 对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置
* 转置可以作用于多维数组

In [33]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [35]:
a.T

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

## 数组连接

有时我们需要将不同的数组按照一定的顺序连接起来：

    concatenate((a0,a1,...,aN), axis=0)
    注意，这些数组要用 () 包括到一个元组中去。

除了给定的轴外，这些数组其他轴的长度必须是一样的。

In [36]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print x.shape
print y.shape

(2, 3)
(2, 3)


默认按照第一维链接

In [39]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

可以执行按照第二维连接

In [40]:
z = concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

## Flatten 数组

flatten 方法的作用是将多维数组转化为1维数组：

In [41]:
a = array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

返回的是数组的深复制，因此，改变 b 并不会影响 a 的值：

In [42]:
b[2] = 5
print a
print b

[[0 1]
 [2 3]]
[0 1 5 3]


## flat 属性

还可以使用数组自带的 flat 属性 , a.flat 相当于返回了所有元组组成的一个迭代器：

In [43]:
a.flat
b = a.flat
b[1]

1

## ravel 方法

除此之外，还可以使用 ravel 方法，ravel 使用高效的表示方式：

In [44]:
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

 修改 b 会改变 a ：

In [45]:
b[2] = 100
print a
print b

[[  0   1]
 [100   3]]
[  0   1 100   3]
