# 生成数据

In [1]:
import torch

## 生成不同维度的数据

生成一个2行3列数值均为1的矩阵

In [4]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

生成一个2行3列数值为0的矩阵

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

生成一个2行3列的随机数值，默认随机数大小为0~1之间

In [7]:
torch.rand(2,3)

tensor([[0.2737, 0.7305, 0.9919],
        [0.7107, 0.4858, 0.2095]])

如果需要生成的随机数为整数，可以用下面的方法：生成一个2行3列的数字为1到10之间的整数的矩阵

In [9]:
torch.randint(1,10,(2,3))

tensor([[7, 2, 2],
        [2, 6, 8]])

生成符合标准正态分布的随机数:

In [10]:
torch.randn(2,3)

tensor([[-0.2606,  0.1281, -0.3551],
        [ 0.5340, -0.7321,  0.3593]])

## 查看数据信息

生成一个2行3列的矩阵

In [12]:
a = torch.tensor([[1,2,3],[4,5,6]])

基于a矩阵的维度生成b矩阵，且指定b矩阵的数据类型

In [15]:
b = torch.rand_like(a,dtype=float)
print(b)

tensor([[0.4248, 0.8795, 0.3839],
        [0.6584, 0.8159, 0.5154]], dtype=torch.float64)


查看b的数据形状

In [16]:
print(b.shape)
print(b.size())

torch.Size([2, 3])
torch.Size([2, 3])


## 修改数据形状

使用view 修改数据的形状，把2行3列的矩阵b，修改成一维矩阵。

In [18]:
c = b.view(6)
print(c)

tensor([0.4248, 0.8795, 0.3839, 0.6584, 0.8159, 0.5154], dtype=torch.float64)


也可以把2行3列修改成3行2列

In [20]:
d = a.view(3,2)
print(d)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


view 相当于reshape，也可以使用reshape来修改数据的形状

In [21]:
e = d.reshape(6)
print(e)

tensor([1, 2, 3, 4, 5, 6])


## 和numpy格式转换
查看矩阵元素的方法

In [24]:
e[1]

tensor(2)

e[1]输出的数据类型为tensor，如果需要python对应的数据类型需要使用下面的方法

In [25]:
e[1].item()

2

In [27]:
import numpy as np

tensor可以直接转换成numpy中的array

In [29]:
f = numpy.array(e)
f

array([1, 2, 3, 4, 5, 6])

把numpy中的array转换成tensor

In [30]:
array = numpy.array([1,2,3])
k = torch.tensor(array)
print(k)

tensor([1, 2, 3])
