# tensor的索引操作

In [1]:
import torch

tensor = torch.arange(2,10)
tensor

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(tensor[3])

tensor(5)


In [4]:
print(tensor[2:5])

tensor([4, 5, 6])


In [5]:
print(tensor[:4])

tensor([2, 3, 4, 5])


In [6]:
print(tensor[-3:])

tensor([7, 8, 9])


In [7]:
index = [1,3,5]
print(tensor[index])

tensor([3, 5, 7])
