# 自动求导

In [1]:
import torch

In [3]:
x = torch.ones((2,2),requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2
z = y ** 2 * 3

In [5]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [6]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
