# 矩阵的基本运算

先导入torch包并定义两个简单的矩阵

In [3]:
import torch

a = torch.randint(2,8,(2,3))
b = torch.randint(2,8,(2,3))
print(a)
print(b)

tensor([[4, 7, 7],
        [5, 2, 5]])
tensor([[7, 4, 2],
        [3, 3, 2]])


## 矩阵加法
矩阵加法就是矩阵对应位置相加，需要保证矩阵的维度是一致的才可以，否则不成功
### 方法1

In [4]:
a+b

tensor([[11, 11,  9],
        [ 8,  5,  7]])

### 方法2

In [5]:
torch.add(a,b)

tensor([[11, 11,  9],
        [ 8,  5,  7]])

### 方法3
注意这里的add_方法。
任何使张量tensor发生变化的操作都有一个前缀'_',例如一下例子的add_

In [8]:
a.add_(b)

tensor([[25, 19, 13],
        [14, 11, 11]])

## 减法

In [9]:
a - b

tensor([[18, 15, 11],
        [11,  8,  9]])

## 乘法

In [10]:
a * b

tensor([[175,  76,  26],
        [ 42,  33,  22]])

## 除法

In [11]:
a / b

tensor([[3.5714, 4.7500, 6.5000],
        [4.6667, 3.6667, 5.5000]])

## 取余

In [15]:
print(a)
print(b)
a % b

tensor([[25, 19, 13],
        [14, 11, 11]])
tensor([[7, 4, 2],
        [3, 3, 2]])


tensor([[4, 3, 1],
        [2, 2, 1]])

## 取整

In [16]:
print(a)
print(b)
a // b

tensor([[25, 19, 13],
        [14, 11, 11]])
tensor([[7, 4, 2],
        [3, 3, 2]])


tensor([[3, 4, 6],
        [4, 3, 5]])

# 矩阵的乘法

2行3列的矩阵乘以3行5列的矩阵，得到2行5列的矩阵。

矩阵乘法需要保证2个矩阵的数据类型一致。

In [17]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
a = torch.randint(2,8,(2,3))

In [19]:
torch.matmul(tensor,a)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x5 and 2x3)

In [20]:
tensor.dtype

torch.float32

In [22]:
a = a.float()
a.dtype

torch.float32

In [24]:
torch.matmul(a,tensor)

tensor([[17., 17., 17., 17., 17.],
        [ 8.,  8.,  8.,  8.,  8.]])

# 矩阵的转置

In [25]:
a.T

tensor([[5., 3.],
        [7., 2.],
        [5., 3.]])

# 其他基本运算

## 矩阵元素求和

In [26]:
sample = torch.rand(2,3)
sample

tensor([[0.1446, 0.6382, 0.6163],
        [0.2636, 0.0493, 0.5581]])

In [27]:
torch.sum(sample)

tensor(2.2702)

## 矩阵求平均数

In [28]:
torch.mean(sample)

tensor(0.3784)

## 矩阵求最大值和最小值

In [31]:
torch.max(sample)

tensor(0.6382)

In [32]:
torch.min(sample)

tensor(0.0493)

## 求矩阵最大值和最小值的索引位置

In [33]:
torch.argmax(sample)

tensor(1)

In [34]:
torch.argmin(sample)

tensor(4)

## 求矩阵的中位数

In [35]:
torch.median(sample)

tensor(0.2636)

## 矩阵的开方

In [37]:
torch.sqrt(sample)

tensor([[0.3803, 0.7989, 0.7851],
        [0.5134, 0.2221, 0.7471]])

## 矩阵的多次方

In [39]:
sample ** 2

tensor([[0.0209, 0.4073, 0.3799],
        [0.0695, 0.0024, 0.3115]])

In [40]:
sample ** 3

tensor([[3.0265e-03, 2.5994e-01, 2.3413e-01],
        [1.8316e-02, 1.1996e-04, 1.7384e-01]])