# 学习关于pytorch的基本概念
## tensor

In [1]:
import torch

In [8]:
#定义一维tensor
a = torch.tensor([1,2,3],dtype=int)
print(a)

tensor([1, 2, 3])


In [5]:
b = torch.tensor([4,5,6],dtype=float)
print(b)

tensor([4., 5., 6.], dtype=torch.float64)


In [9]:
#定义二维tensor
c = torch.tensor([[1,2,3,4],
                 [3,4,5,6],
                [6,7,8,9]])

In [10]:
print(c)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [6, 7, 8, 9]])


In [11]:
#显示数据维度
c.ndim

2

In [12]:
#查看数据形状
c.shape

torch.Size([3, 4])

In [13]:
#查看数据形状-方法
c.size()

torch.Size([3, 4])

In [15]:
#查看数据类型
c.dtype

torch.int64