# 数组形状


In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 修改数组形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

将形状修改为2乘3

In [3]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

与之对应的方法是 reshape ，但它不会修改原来数组的值，而是返回一个新的数组：

In [4]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

shape 和 reshape 方法不能改变数组中元素的总数，否则会报错

## 使用 newaxis 增加数组维数

In [8]:
a = arange(3)
a

array([0, 1, 2])

In [9]:
shape(a)

(3,)

In [10]:
y = a[newaxis, :]
shape(y)

(1, 3)

In [11]:
y

array([[0, 1, 2]])

根据插入位置的不同，可以返回不同形状的数组

In [12]:
y = a[:,newaxis]
shape(y)

(3, 1)

## squeeze 方法去除多余的轴

In [15]:
a = arange(6)
a.shape = (2,1,3)
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [16]:
b = a.squeeze()
b.shape

(2, 3)

In [17]:
b

array([[0, 1, 2],
       [3, 4, 5]])

squeeze 返回一个将所有长度为1的维度去除的新数组。

## 数组转置

使用 transpose 返回数组的转置，本质上是将所有维度反过来：

In [18]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [19]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])